WordPress/wpcs-docs

wordpress-coding-standards/html.md

In all code examples on the web page "[HTML Coding Standards](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/html/#self-closing-elements)", the left brackets of all tags are displayed incorrectly.
Therefore, I fixed all the code examples so that the left brackets of the tags were set in the same way as the right ones:  `&lt;` instead of `<`.

Fix left angle brackets in tags inside examples

---

inline-documentation-standards.md

The site `jaco.by` is now a parked domain. I think I've found the new site for the blog post referenced in the Resources section.

URL changed

---

inline-documentation-standards/php.md

This PR updates the inline PHP docs from the latest revision made 19 June 2020
> https://make.wordpress.org/core/wp-admin/revision.php?revision=81856&gutenberg=true

Update PHP Inline Docs per Revision 81856

---

wordpress-coding-standards/php.md

Fixes #38
This PR tests the markdown passer by using `&quest;` instead of `?` for opening and closing PHP tags

Try `&quest;` HTML Entity for `?` PHP tags

---

wordpress-coding-standards/css.md

In line 9-13 of the sample it looks like the text formatting is incorrect and the information about not using unit for line height is missing

Update css.md - amend sample of incorrect values

---

changelog.md
inline-documentation-standards/javascript.md
inline-documentation-standards/php.md
styleguide.md
wordpress-coding-standards/css.md
wordpress-coding-standards/html.md
wordpress-coding-standards/javascript.md
wordpress-coding-standards/php.md

* Switches to using Markdown code fence notation instead of shortcodes
* Removes HTML entity substitutions as they are no longer necessary.
Style guide:
* Removes 'Shortcodes' section as shortcodes are no longer recommended. Markdown code fences, as described in prior section, is the preferred method.
* Escapes the code fence examples so the Markdown code fence notation themselves are shown. The examples intend to demonstrate the use of code fences (often with language hinting) but when unescaped this results in the code being formatted instead of shown.
* Adds an 'HTML' example to the 'Fenced Code Blocks' section as that appears to have been an oversight.
Fixes #44.

Switch to using Markdown code fence notation instead of shortcodes and update style guide accordingly.

---

wordpress-coding-standards/php.md

This addition will allow https://github.com/WordPress/WordPress-Coding-Standards/pull/1802 to be merged to the coding standards.
This will encourage having one class/interface/trait per file.
Feel free to suggest better wording, I tried to be as clear as possible.

Adding one object structure per file

---

wordpress-coding-standards/php.md

We DO indent inside divs and we DON'T indent inside PHP open/close tags - correct?
In which case the indentation here seems incorrect - removing a level of tab from the div fixes both issues

Adjust a tab level to fix div & PHP open/close

---

inline-documentation-standards/javascript.md

See https://github.com/jsdoc/jsdoc/issues/1642
At the moment, http://usejsdoc.org/ resolves to a 'domain has expired' page at hover.com

broken link to usejsdoc.org

---

inline-documentation-standards/javascript.md

Includes:
* Removing stray unicode artifacts.
* Improving formatting consistency in a couple of places.
I.e. having "Good"/"Bad" both wrapped in emphasis, having the `:` in lists not included in the bold tags, refering to the correct tags in some examples - most for `@deprecated`.
* Being more liberal with backticks around documentation `@tags`, like in the tables.
* Improving accessibility by not using "here" as link text.
* Removing trailing spaces.
**Notes**:
* The formatting around the `[tip]` should be double-checked as I'm not sure if the shortcode doesn't break now the contents is reformatted.
* There are a few "inline headers" (using `**` not `##..`) in the "Formatting Guidelines" section, about which I wonder if those shouldn't be changed to proper headers.
See: …

JS Docs: convert from HTML to markdown

---

wordpress-coding-standards/css.md

Let's ensure the global docs are less US-centric for numerical dates.

Use international date format

---

wordpress-coding-standards/javascript.md

Referring to the issue I created: https://github.com/WordPress/wpcs-docs/issues/78
There is no Naming Conventions topic or #naming-conventions anchor within the page. Therefore I have removed the link in this PR as it is no longer useful.

Remove Unused Link

---

wordpress-coding-standards/php.md

This is the first part of the updates to the WPCS PHP documentation. In this PR I've gone through the text and replaced all the HTML with markdown syntax.
Some links have been updated - some HTTP to HTTPS replacements; data validation now points to the plugins handbook (as a part of the move from codex to developers documentation); added title refs to trac tickets.
I've looked at the JS coding standards documentation and markdown is used there, so don't see why it shouldn't be used here as well.
The second part of the updates will see what rules can be added from the [make post](https://make.wordpress.org/core/2020/03/20/updating-the-coding-standards-for-modern-php/) in 2020. There are some ongoing discussions that are not resolved, but I'll add only the one that nobody had any issues …

Content update changes in PHP Coding Standards

---

wordpress-coding-standards/php.md

This PR contains the suggestions and fixes for the code examples based on comments from #65 PR.
Mostly fixed the escaping issues, some comments missing full stops at the end, and the like.

Fix the code examples

---

wordpress-coding-standards/php.md

Closes #93 
Grouped similar chapters in a logical structure.
Reviewing this from a code comparison view might be... challenging.
I recommend just opening the new structure and the old one and comparing if everything was copied over correctly.
The proposed chapter grouping is the following:
~~~text
General
Opening and Closing PHP Tags
No Shorthand PHP Tags
Single and Double Quotes
Naming
Naming Conventions
Interpolation for Naming Dynamic Hooks
Whitespace
Space Usage
Indentation
Remove Trailing Spaces
Formatting
Brace Style
Declaring Arrays
Multiline Function Calls
Object-Oriented Programming
Only One Object Structure (Class/Interface/Trait) per File
Control Structures
Use `elseif`, Not `else if`
Yoda Conditions
Operators
Ternary Operator
Error Control Operator `@`
Database
Database …

Reorganized the chapters in the PHP handbook

---

inline-documentation-standards/php.md

* Remove reference to PSR5 as the current version of PSR5 is pretty different from the PSR5 draft which was used at the time this was written.
* Remove outdated naming references.
* Clarify when `@access` should be used (now often used incorrectly in Core as it isn't specified what is meant by "in limited circumstances").
* Clarify the correct use of `{@internal ...}.
* Make the list of deprecated tags a little more complete.
* Add link to draft PSR19.

PHP Docs: various small textual updates

---

wordpress-coding-standards/php.md

This is the first PR that aims to add the additions of 'modern' coding standards in the WP PHP Coding Standards handbook based on the [make post](https://make.wordpress.org/core/2020/03/20/updating-the-coding-standards-for-modern-php/) created by Juliette Reinders Folmer over two years ago.
The aim is to add some 15ish new additions from the post (maybe less because some proposals do need additional discussion) to the handbook so that we have guides in place for anybody who uses modern code additions like namespaces and traits in their code, but wishes to align it to WordPress Coding Standards rules.
This will also enable us to add the rules to the wpcs sniffs so that these checks are automated across the WordPress Core as well. 
I tried to distill the make post so that the handbook …

Add namespace declaration section

---

wordpress-coding-standards/php.md

The PR adds rules about import `use` statements in the code and is the continuation of the additions of 'modern' PHP code in the WordPress PHP Coding Standards handbook based on the [make post](https://make.wordpress.org/core/2020/03/20/updating-the-coding-standards-for-modern-php/) by Juliette Reinders Folmer.
I'd hold off of a review until the above PR is merged.

Add import use statements section

---

wordpress-coding-standards/php.md

This PR depends on #100. Once that is merged, this PR should be rebased to the master branch.
The PR adds rules about the trait formatting rules and is the continuation of the additions of 'modern' PHP code in the WordPress PHP Coding Standards handbook based on the [make post](https://make.wordpress.org/core/2020/03/20/updating-the-coding-standards-for-modern-php/) by Juliette Reinders Folmer.

Trait formatting

---

wordpress-coding-standards/php.md

This PR depends on #113. Once that is merged, this PR should be rebased to the master branch.
The PR adds rules about disallowing the usage of the backtick operator and is the continuation of the additions of 'modern' PHP code in the WordPress PHP Coding Standards handbook based on the [make post](https://make.wordpress.org/core/2020/03/20/updating-the-coding-standards-for-modern-php/) by Juliette Reinders Folmer.

Shell commands

---

wordpress-coding-standards/php.md

This PR depends on #109. Once that is merged, this PR should be rebased to the master branch.
The PR adds rules about the function closing brace and is the continuation of the additions of 'modern' PHP code in the WordPress PHP Coding Standards handbook based on the [make post](https://make.wordpress.org/core/2020/03/20/updating-the-coding-standards-for-modern-php/) by Juliette Reinders Folmer.

Function closing brace

---

wordpress-coding-standards/php.md

This PR depends on #111. Once that is merged, this PR should be rebased to the master branch.
The PR adds rules about the increment/decrement operators and is the continuation of the additions of 'modern' PHP code in the WordPress PHP Coding Standards handbook based on the [make post](https://make.wordpress.org/core/2020/03/20/updating-the-coding-standards-for-modern-php/) by Juliette Reinders Folmer.

Increment decrement operators

---

wordpress-coding-standards/php.md

Update the list in the spacing section and added some new code examples.
The PR adds rules about the additional operators and is the continuation of the additions of 'modern' PHP code in the WordPress PHP Coding Standards handbook based on the [make post](https://make.wordpress.org/core/2020/03/20/updating-the-coding-standards-for-modern-php/) by Juliette Reinders Folmer.

Instanceof and other operators

---

wordpress-coding-standards/php.md

This PR depends on #101. Once that is merged, this PR should be rebased to the master branch.
The PR adds rules about the type declaration rules and is the continuation of the additions of 'modern' PHP code in the WordPress PHP Coding Standards handbook based on the [make post](https://make.wordpress.org/core/2020/03/20/updating-the-coding-standards-for-modern-php/) by Juliette Reinders Folmer.

Type declarations

---

wordpress-coding-standards/php.md

This PR depends on #106. Once that is merged, this PR should be rebased to the master branch.
The PR adds rules about declaring visibility modifiers and is the continuation of the additions of 'modern' PHP code in the WordPress PHP Coding Standards handbook based on the [make post](https://make.wordpress.org/core/2020/03/20/updating-the-coding-standards-for-modern-php/) by Juliette Reinders Folmer.

Visibility should always be declared

---

wordpress-coding-standards/php.md

This PR depends on #102. Once that is merged, this PR should be rebased to the master branch.
The PR adds rules about the `::class` constant and is the continuation of the additions of 'modern' PHP code in the WordPress PHP Coding Standards handbook based on the [make post](https://make.wordpress.org/core/2020/03/20/updating-the-coding-standards-for-modern-php/) by Juliette Reinders Folmer.

The ::class constant

---

wordpress-coding-standards/php.md

This PR depends on #110. Once that is merged, this PR should be rebased to the master branch.
The PR adds rules about the include/require statements and is the continuation of the additions of 'modern' PHP code in the WordPress PHP Coding Standards handbook based on the [make post](https://make.wordpress.org/core/2020/03/20/updating-the-coding-standards-for-modern-php/) by Juliette Reinders Folmer.

Include require statements

---

wordpress-coding-standards/php.md

This PR depends on #104. Once that is merged, this PR should be rebased to the master branch.
The PR adds rules about the spread operator and is the continuation of the additions of 'modern' PHP code in the WordPress PHP Coding Standards handbook based on the [make post](https://make.wordpress.org/core/2020/03/20/updating-the-coding-standards-for-modern-php/) by Juliette Reinders Folmer.

Spread operator

---

wordpress-coding-standards/php.md

This PR depends on #105. Once that is merged, this PR should be rebased to the master branch.
The PR adds rules about writing the magic constants and is the continuation of the additions of 'modern' PHP code in the WordPress PHP Coding Standards handbook based on the [make post](https://make.wordpress.org/core/2020/03/20/updating-the-coding-standards-for-modern-php/) by Juliette Reinders Folmer.

Magic constants

---

wordpress-coding-standards/php.md

This PR depends on #107. Once that is merged, this PR should be rebased to the master branch.
The PR adds rules about the order of property and method modifiers and is the continuation of the additions of 'modern' PHP code in the WordPress PHP Coding Standards handbook based on the [make post](https://make.wordpress.org/core/2020/03/20/updating-the-coding-standards-for-modern-php/) by Juliette Reinders Folmer.

Property and method modifier order

---

wordpress-coding-standards/php.md

This PR depends on #108. Once that is merged, this PR should be rebased to the master branch.
The PR adds rules about the object instantiation and is the continuation of the additions of 'modern' PHP code in the WordPress PHP Coding Standards handbook based on the [make post](https://make.wordpress.org/core/2020/03/20/updating-the-coding-standards-for-modern-php/) by Juliette Reinders Folmer.

Object instantiation

---

wordpress-coding-standards/php.md

This same rule is also mentioned in the type declaration section (second paragrah).
Ref: https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#type-declarations

PHP docs: remove a duplication

---

wordpress-coding-standards/php.md

Most of this has already been fixed in WP Core as part of making Core compatible with PHP 8.0 and it would be great if no new instances of this issue would be introduced.
Ref:
* https://core.trac.wordpress.org/ticket/51553
* https://core.trac.wordpress.org/ticket/55327
* https://core.trac.wordpress.org/ticket/55650
* https://core.trac.wordpress.org/ticket/56788

PHPdocs: discourage use of reserved keywords for parameter names

---

wordpress-coding-standards/php.md

The three exceptions which were previously listed have recently been fixed in Core, so the exception should be removed.
At the same time, we should make the exception for test files explicit with an eye on the upstream changes in PHPUnit.
Refs:
* https://core.trac.wordpress.org/changeset/54254
* https://core.trac.wordpress.org/ticket/53010
* WordPress/WordPress-Coding-Standards#1995
* sebastianbergmann/phpunit#4109

PHP: adjust the file name rule

---

wordpress-coding-standards/html.md

Existing path url is duplicated and the link is therefore broken: https://creativecommons.org/licenses/by-nc-sa/3.0/http://creativecommons.org/licenses/by-nc-sa/3.0/
I have reduced to the correct url: https://creativecommons.org/licenses/by-nc-sa/3.0/

Updated external incorrect url

---

wordpress-coding-standards/accessibility.md

- Correct broken TPGI links (Paciello Group is no more)
- make UK government links more specific
- add Section 508, WP A11y Meetup, WP A11y Day, Equalize Digital, and Mozilla Developer Docs

Improvements to accessibility links

---

wordpress-coding-standards/php.md

Allowing a single conflict resolution statement on the same line as the `use` decreases readability.
Changing this to a multi-line statement, with each conflict resolution statement on its own line, also improves consistency with other WP Core rules around the use of braces, as it makes the brace layout consistent with the expected brace layout for various control structures.

PHP/Trait Use Statements: minor tweak to "correct" example

---

inline-documentation-standards/php.md
wordpress-coding-standards.md

See https://core.trac.wordpress.org/ticket/59619 and https://github.com/WordPress/wordpress-develop/pull/5484#pullrequestreview-1679058155: The current explanation that `@return void` should only be used outside of bundled themes is missing two other areas where that rule does not apply.

Clarify exceptions for using `@return void`

---

wordpress-coding-standards/php.md

The documentation was pointing to the now abandoned https://github.com/squizlabs/PHP_CodeSniffer. This PR updates the link to point to https://github.com/PHPCSStandards/PHP_CodeSniffer/
Kudos to @ironprogrammer who found this and pinged me about it.
I searched this repository for `squizlabs` and this is the single occurrence that I found.

Update link to PHPCS to point to the new repository

---

wordpress-coding-standards/php.md

Whilst reading the developer docs I found a minor typo. This PR should fix said typo.

Fix a typo in the php documentation where Wordpress is missing an s

---

wordpress-coding-standards/css.md

Update css.md - correct grammar error

---

wordpress-coding-standards/javascript.md

Fixed incorrect Markdown for a link with a title attribute.

JS Docs: Fix broken Markdown for link title

---

wordpress-coding-standards/php.md

This fixes #143 
Also taken care of @jrfnl 's comment on slack that autoloading only applies to classes and not to functions or constants.

require/import vs require/include in PHP Coding Standards Documentation. - Fix for #143

---

.github/workflows/qa.yml
_typos.toml
wordpress-coding-standards/css.md
wordpress-coding-standards/javascript.md
wordpress-coding-standards/php.md

I was having a play with adding a spellchecker to the WPCS repo and when doing so, realized that some of the flagged texts - particularly in the WPCS-Core `ruleset.xml` file - are coming from this repo, so should probably be fixed here first.
So, this commit adds a basic workflow with a spellcheck job.
Notes:
* The "Typos" tool is known for having a low false positive ratio and being aware of code contexts. However, this also means, it may at times miss some things.
When selecting it, I deemed the low false positive ratio more important.
* The language has been set to `en-US` as that's the language predominantly used for the WordPress documentation.
This does mean that various phrases using `en-GB` spelling will need to be fixed/updated.
* I've named the workflow file `qa.yml` with a …

GH Actions: add spellcheck + fix a few typos

---

wordpress-coding-standards/php.md

These were removed from PHP in PHP 7.0 and WP nowadays has a PHP 7.2 minimum, which means these function cannot be used anyhow, so this is no longer relevant.
Related to https://github.com/WordPress/WordPress-Coding-Standards/issues/2612

PHP: remove reference to POSIX regex functions
